version: "3.7"

services:
  cart:
    restart: always  # Should keep restarting Spring Boot until the DB is up
    build:
      context: .
      dockerfile: Dockerfile.micrometer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cart?currentSchema=public
      SPRING_DATASOURCE_USERNAME: supershop
      SPRING_DATASOURCE_PASSWORD: supershop
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
      MANAGEMENT_METRICS_TAGS_APPLICATION: shopping-cart
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: supershop
      POSTGRES_PASSWORD: supershop
      POSTGRES_DB: cart
    ports:
      - "5432:5432"

  agent:
    image: docker.io/grafana/agent:latest
    environment:
      AGENT_MODE: flow
      GRAFANA_CLOUD_API_KEY: "${GRAFANA_CLOUD_API_KEY}"
      LOGS_USERNAME: "${LOGS_USERNAME}"
      METRICS_USERNAME: "${METRICS_USERNAME}"
      TRACES_USERNAME: "${TRACES_USERNAME}"
    command:
      - "run"
      - "/etc/agent/config.river"
    volumes:
      - ./agent.micrometer.river:/etc/agent/config.river:z
